### ISSUE TITLE
User Resource

### ISSUE THREAD

**Issue by jacksgt** [jacksgt/mgmt#1]
New Resource 'User' used for managing Users and Groups.

Graph:
```yaml
---
graph: mygraph
resources:
    user:
        - name: 'john'
          type: 'user'
          gecos: 'John Doe,,,,' // https://en.wikipedia.org/wiki/Gecos_field
          shell: '/bin/sh' // defaults to /bin/sh
          uid: '1000' //defaults to next available
          gid: '1000' // defaults to usergroup
          groups: [ 'docker', 'sudo' ]
          homedir: '/home/john'
          createhome: true // defaults to true
          password: 's3cr3t'
          system: false // uid within 1-1000 // actually UID_MIN-UID_MAX
         usergroup: true // create group for this user
       - name: 'sudo'
         type: 'group'
         gid: '1598' // defaults no next available
         system: false // gid within GID_MIN-GID_MAX
```

see [useradd(8)](https://manpages.debian.org/jessie/passwd/useradd.8.en.html) and [groupadd(8)](https://manpages.debian.org/jessie/passwd/groupadd.8.en.html)
